version: '3.4'

services:
  chatserver.api:
    container_name: Turbo
    env_file: .env
    restart: unless-stopped
    ports:
      - "443:8080"
    image: ${DOCKER_REGISTRY-}chatserverapi
    build:
      context: .
      dockerfile: ./Turbo/Dockerfile
    volumes:
      - ./chatappclient-93ff4-firebase-adminsdk-k2t2q-0f5d59c785.json:/app/chatappclient-93ff4-firebase-adminsdk-k2t2q-0f5d59c785.json
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
  
  redis:
    container_name: TurboRedis
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"